apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4xMjM= #  mysql echo -n "admin" | base64
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: YWRtaW4xMjM=  # mysql echo -n "admin123" | base64
