apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306 # port number
  clusterIP: None
  selector:
    app: mysql
    project: roboshop
    tier: db
