apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
   app: redis
   project: roboshop
   tier: db
spec:
  selector:
    matchLabels:
      app: redis
      project: roboshop
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "redis"
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        app: redis
        project: roboshop
        tier: db
    spec:
      containers:
      - name: redis
        image: redis
        volumeMounts:
        - name: redis 
          mountPath: /data # redis path
  volumeClaimTemplates:
  - metadata:
      name: redis 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"  # Changed from ebs-sc to gp2
      resources:
        requests:
          storage: 1Gi