apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    app: rabbitmq
    project: roboshop
    tier: db
spec:
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672 # port number
  clusterIP: None
  selector:
    app: rabbitmq
    project: roboshop
    tier: db
