apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    app: rabbitmq
    project: roboshop
    tier: db
spec:
  serviceName: "rabbitmq"
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: rabbitmq  
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        app: rabbitmq
        project: roboshop
        tier: db
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
          envFrom:
            - secretRef:
                name: rabbitmq
          volumeMounts:
            - name: rabbitmq
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "ebs-sc"
        resources:
          requests:
            storage: 2Gi
